= Pymontrace
:toc:

// TODO: have a quickstart

// TODO: have some nice one-liners


== The pymontrace language

The pymontrace language is heavily inspired the D language of Dtrace.

In general it follows the form

....
program ::= ( probe-spec probe-action )*

probe-spec = probe-name ":" probe-arg1 ":" probe-arg2

probe-action = "{{" python-program-text "}}"

probe-name = "line" | ...
....


.Example pymontrace program
----
line:*/some-file.py:123 {{
    pmt.print("a =", a)
    if b is not None:
        pmt.vars.b = pmt.count()
}}

pymontrace::END {{
    pmt.print("b =", pmt.vars.b)
}}
----


The python blocks are run in the context of the probe site.
They have access to all the local variables.


== Special variables

The executing python actions, in addition to the program context, have access
to a helper module called the `pmt` module.

The `pmt` module contains a number of helper functions and special properties.


=== `pmt` standard functions

[cols="1,3"]
|===
| `print(arg1, arg2, ...)`
| Works just like the python `print` builtin, except that it sends the
output back to the tracer.

// TODO: have some kind of pmt.exit() function
|===


=== `pmt` aggregation functions

Aggregation functions are special and must be assigned to
pymontrace variables or into map entries.

[cols="1,3"]
|===
| Function | Description

| `count()`
| Counts the number of times it is hit

| `sum(arg)`
| Adds `arg` to the sum.

| `max(arg)`
| Computes the maximum over supplied arguments.

| `min(arg)`
| Computes the minimum over supplied arguments.

|===

=== `pmt` properties

[cols="1,5"]
|===
| Property | Description

| `vars`
| `vars` is a namespace for holding user variables. This can be used to
store values between probe executions.

| `maps`
| `maps` is a namespace for holding user maps (dictionaries). Any non-empty
maps will printed out at the end of tracing. They are most useful when
combined with aggregations.

|===


== Probes

[cols="1,3"]
|===
| Probe Name | Description

| `pymontrace::BEGIN`, `pymontrace::END`
| `BEGIN` is executed after pymontrace successfully connects to a target.
`END` is executed if tracing ends normally and before the program itself
terminates.

| `line:__filepath__:__line number__`
| Executes its action just before the matched line executes.
It corresponds to https://docs.python.org/3/library/sys.monitoring.html#monitoring-event-LINE[sys.monitoring.events.LINE]
when tracing Python 3.12 and later.
It corresponds to the https://docs.python.org/3/library/sys.html#sys.settrace[`'line'` trace event]
when tracing Python 3.11 and earlier.

| xref:_probe_func[
`func:__qpath__:start`,
`func:__qpath__:yield`,
`func:__qpath__:resume`,
`func:__qpath__:return`,
`func:__qpath__:unwind`
]
| Entry and exit points of python functions.

| `call:__qpath__:before`,
`call:__qpath__:after`,
| Before and after making a function call. The context is within the caller.
_Not yet implemented_.

|===


// Maybe we should have non-table sections like they do in the bpftrace docs

=== `pymontrace::BEGIN`

`BEGIN` can be useful to set up initial values of variables.

Since it runs in the context of the traced target, it can also be used
to do simple state checks.

Another use for `BEGIN` is to import modules and define helper functions.
Since importing in python can be very expensive you'll want to avoid that
in a tight loop.
A way around that would be to import and assign to a variable on `pmt.vars`.

.Example showing import in `BEGIN`
----
pymontrace::BEGIN {{
    import base64
    pmt.vars.b64decode = base64.b64decode
}}

line:*/target.py:123 {{
    pmt.print(pmt.vars.b64decode(some_base64_encoded_value))
}}
----


[#_probe_func]
=== `func:__qpath__:...`

`func` probes are able to monitor the entry and exit points of any python
function.

The `_qpath_` segment is the module qualified function path.

To give an example, let's state the qpaths for if the following was imported
as `import helpers.helpful`

.helpers/helpful.py
[source,python]
----
class Helper:
    def help(self):  # <1>
        pass

def make_helper():  # <2>
    class Elf:
        def help(self):  # <3>
            pass
    return Elf().help()
----
<1> `helpers.helpful.Helper.help`
<2> `helpers.helpful.make_helper`
<3> `helpers.helpful.make_helper.<locals>.Elf.help`


Using a module path based on a reexport will not match.

For example, assuming the next two files are part of the traced process,
the probe spec
`+func:requests.client.exceptions.ClientException.__init__:start+`
will match when `ClientException` is constructed,
whereas
`+func:requests.exceptions.ClientException.__init__:start+`
will not.

.requests/exceptions.py
[,python]
----
from client.exceptions import ClientException
__all__ = ("ClientException",)
----

.requests/clients/exceptions.py
[,python]
----
class ClientException(Exception):
    def __init__(*args):
        ...
----


The following shows the positions of the probe sites in a representative
function

[,python]
----
def example():
    # start
    ...
    # yield
    yield
    # resume

    if ...:
        # unwind
        raise Exception

    # return
    return

async def coro():
    ...
    # yield
    await other()
    # resume
    ...
----

NOTE: Tracking the `unwind` event causes some overhead when any exception is
raised within the target. Whereas, on Python 3.12 and later, tracking
for example `start` only causes overhead in matching functions.

WARNING: `yield` and `resume` only match on Python 3.12 and later.


== Known Issues

=== macOS

* Tracing a python process on macOS which has either it's binary or shared
  objects under a system path is not possible unless
  https://support.apple.com/en-gb/102149[SIP] is
  https://developer.apple.com/documentation/security/disabling-and-enabling-system-integrity-protection[disabled].
  This includes
    1. The system python (`/usr/bin/python3`)
    2. Python installed via the macOS universal installer found on https://python.org
  Versions installed via Homebrew work up to 3.12

* Attaching never succeed on the Python 3.13 installed via Homebrew.
  The build doesn't seem to call `PyEval_SaveThread`.
  Should be fixable.
