name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: |
        pipx run build --sdist
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists-sdist
        path: dist/

  build-amd64:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    steps:
    - uses: actions/checkout@v4
    - name: Build package
      run: |
        for V in 3.9; do
          python${V} -m build --installer=uv
        done
    - name: Run auditwheel
      run: |
        auditwheel repair -w wheelhouse/ dist/*.whl
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists-amd64
        path: wheelhouse/

  build-arm64:
    runs-on: ubuntu-24.04-arm
    container:
      image: quay.io/pypa/manylinux_2_28_aarch64
    steps:
    - uses: actions/checkout@v4
    - name: Build package
      run: |
        for V in 3.9; do
          python${V} -m build --installer=uv
        done
    - name: Run auditwheel
      run: |
        auditwheel repair -w wheelhouse/ dist/*.whl
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists-arm64
        path: wheelhouse/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Build package
        run: |
          make build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists-macos
          path: dist/*.whl


  publish:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs:
      - build-sdist
      - build-amd64
      - build-arm64
      - build-macos
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/pymontrace

    steps:
    - name: Retrieve sdist
      uses: actions/download-artifact@v4
      with:
        name: release-dists-sdist
        path: dist/
    - name: Retrieve amd64
      uses: actions/download-artifact@v4
      with:
        name: release-dists-amd64
        path: dist/
    - name: Retrieve arm64
      uses: actions/download-artifact@v4
      with:
        name: release-dists-arm64
        path: dist/
    - name: Retrieve macos
      uses: actions/download-artifact@v4
      with:
        name: release-dists-macos
        path: dist/

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
