name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: |
        pipx run build --sdist
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists-sdist
        path: dist/

  build-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            image: quay.io/pypa/manylinux_2_28_x86_64
            artifact: release-dists-amd64
          - runner: ubuntu-24.04-arm
            image: quay.io/pypa/manylinux_2_28_aarch64
            artifact: release-dists-arm64
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v4
    - name: Build package
      run: |
        for V in 3.9; do
          python${V} -m build --installer=uv
        done
    - name: Run auditwheel
      run: |
        auditwheel repair -w wheelhouse/ dist/*.whl
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: wheelhouse/

  build-macos:
    # Creates universal2 wheels that are compatible with macos 10.13
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Build package
        run: |
          pipx run build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists-macos
          path: dist/*.whl

  publish:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs:
      - build-sdist
      - build-linux
      - build-macos
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/pymontrace

    steps:
    - name: Retrieve sdist
      uses: actions/download-artifact@v4
      with:
        name: release-dists-sdist
        path: dist/
    - name: Retrieve amd64
      uses: actions/download-artifact@v4
      with:
        name: release-dists-amd64
        path: dist/
    - name: Retrieve arm64
      uses: actions/download-artifact@v4
      with:
        name: release-dists-arm64
        path: dist/
    - name: Retrieve macos
      uses: actions/download-artifact@v4
      with:
        name: release-dists-macos
        path: dist/

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
